"""CMake file generation for the project-rooted codegen pipeline.

Generates three CMake files per project:
- ``definitions.cmake`` — compile definitions with feature flags
- ``features.cmake`` — feature option declarations and dependency checks
- ``sources.cmake`` — source file listings, include directories, Apple framework properties

All generation is model-driven from ``IRProject`` — no per-project branching.
"""
from __future__ import annotations

from typing import cast

from tools.codegen.project_c_backend import (
    IRClass,
    IREnum,
    IRImplementation,
    IRInterface,
    IROutputTarget,
    IRProject,
    class_defs_output,
    implementation_defs_output,
    implementation_internal_output,
    implementation_private_output,
    interface_api_output,
    snake_name,
)
from tools.codegen.project_ir import IRExternalLibrary, IRFeatureRequire
from tools.codegen.project_ir import IRFeature


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def feature_flag_name(prefix: str, entity_name: str) -> str:
    """Derive the CMake feature flag from a project prefix and entity name.

    E.g. ``feature_flag_name("vscr", "ratchet session")`` → ``"VSCR_RATCHET_SESSION"``.
    """
    return f"{prefix.upper()}_{snake_name(entity_name).upper()}"


def _cmake_license_block(license_text: str) -> str:
    if not license_text:
        return ""
    lines = ["#   @license", "#   " + "-" * 73]
    for line in license_text.strip().splitlines():
        line = line.strip()
        lines.append(f"#   {line}" if line else "#")
    lines.append("#   " + "-" * 73)
    return "\n".join(lines)


def _cmake_prologue(license_text: str) -> str:
    """Return the standard prologue: license + warning + include_guard."""
    parts: list[str] = []
    lic = _cmake_license_block(license_text)
    if lic:
        parts.append(lic)
    parts.append("")
    parts.append("#   @warning")
    parts.append("#   " + "-" * 73)
    parts.append("#   This file is fully generated by script 'cmake_files_codegen.gsl'.")
    parts.append("#   It can be changed temporary for debug purposes only.")
    parts.append("#   " + "-" * 73)
    parts.append("#   @end")
    parts.append("")
    parts.append("")
    parts.append("include_guard()")
    return "\n".join(parts)


def _target_check(project_name: str) -> str:
    return (
        f"if(NOT TARGET {project_name})\n"
        f'    message(FATAL_ERROR "Expected target \'{project_name}\' to be defined first.")\n'
        f"endif()"
    )


def _collect_feature_entities(project_ir: IRProject) -> list[tuple[str, str]]:
    """Collect (feature_flag, description) pairs for all feature-bearing entities.

    Returns them in project-XML order: LIBRARY, project features, classes,
    interfaces, implementations.
    """
    prefix = project_ir.prefix
    PREFIX = prefix.upper()
    entries: list[tuple[str, str]] = []

    # LIBRARY is always first
    entries.append((f"{PREFIX}_LIBRARY", f"Enable build of the '{project_ir.name}' library"))

    # Project-level features (e.g. multi_threading)
    for feat in project_ir.features:
        entries.append((feature_flag_name(prefix, feat.name), feat.description or f"Enable feature '{feat.name}'."))

    # Classes
    for cls in project_ir.classes:
        entries.append((feature_flag_name(prefix, cls.name), f"Enable class '{cls.name}'."))

    # Interfaces
    for iface in project_ir.interfaces:
        entries.append((feature_flag_name(prefix, iface.name), f"Enable interface '{iface.name}'."))

    # Implementations
    for impl in project_ir.implementations:
        entries.append((feature_flag_name(prefix, impl.name), f"Enable implementation '{impl.name}'."))

    return entries


# ---------------------------------------------------------------------------
# definitions.cmake
# ---------------------------------------------------------------------------

def generate_definitions_cmake(project_ir: IRProject, license_text: str = "") -> str:
    """Generate ``definitions.cmake`` content for a project."""
    PREFIX = project_ir.prefix.upper()
    lines: list[str] = []

    lines.append(_cmake_prologue(license_text))
    lines.append("")
    lines.append(_target_check(project_ir.name))
    lines.append("")
    lines.append(f"target_compile_definitions({project_ir.name}")
    lines.append("        PUBLIC")
    lines.append(f"            $<BUILD_INTERFACE:{PREFIX}_INTERNAL_BUILD>")
    lines.append(f'            "{PREFIX}_SHARED_LIBRARY=$<BOOL:${{BUILD_SHARED_LIBS}}>"')

    for flag, _desc in _collect_feature_entities(project_ir):
        lines.append(f'            "{flag}=$<BOOL:${{{flag}}}>"')

    lines.append("        )")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# features.cmake
# ---------------------------------------------------------------------------

def _resolve_requirement_feature(
    req_kind: str,
    req_name: str,
    req_project: str | None,
    *,
    project_ir: IRProject,
) -> str | None:
    """Resolve a requirement to its CMake feature flag name.

    Returns None if the requirement doesn't map to a feature (e.g. header requires).
    """
    # Determine the prefix for the target project
    if req_project:
        target_prefix = None
        for fp in getattr(project_ir, 'fallback_projects', None) or []:
            if fp.name == req_project:
                target_prefix = fp.prefix
                break
        if target_prefix is None:
            # Static fallback
            prefix_map = {"common": "vsc", "foundation": "vscf", "ratchet": "vscr", "phe": "vsce"}
            target_prefix = prefix_map.get(req_project, req_project)
    else:
        target_prefix = project_ir.prefix

    if req_kind in ("class", "impl", "interface"):
        return feature_flag_name(target_prefix, req_name)
    elif req_kind == "feature":
        return feature_flag_name(target_prefix, req_name)
    elif req_kind == "module":
        # Modules don't have feature flags — they're unconditional
        return None
    return None


def generate_features_cmake(project_ir: IRProject, license_text: str = "") -> str:
    """Generate ``features.cmake`` content for a project."""
    lines: list[str] = []

    lines.append(_cmake_prologue(license_text))
    lines.append("")

    entities = _collect_feature_entities(project_ir)

    # option() declarations
    for flag, desc in entities:
        lines.append(f'option({flag} "{desc}" ON)')

    # mark_as_advanced()
    lines.append("mark_as_advanced(")
    for flag, _desc in entities:
        lines.append(f"        {flag}")
    lines.append("        )")
    lines.append("")

    # Dependency checks — iterate classes, interfaces, implementations
    def _emit_dep_checks(entity_name: str, requirements: list) -> None:
        source_flag = feature_flag_name(project_ir.prefix, entity_name)
        for req in requirements:
            dep_flag = _resolve_requirement_feature(
                req.kind, req.name, req.attrs.get("project"),
                project_ir=project_ir,
            )
            if dep_flag is None or dep_flag == source_flag:
                continue
            if req.attrs.get("is_optional") == "1":
                continue
            lines.append(f"if({source_flag} AND NOT {dep_flag})")
            lines.append('    message("-- error --")')
            lines.append('    message("--")')
            lines.append(f'    message("Feature {source_flag} depends on the feature:")')
            lines.append(f'    message("     {dep_flag} - which is disabled.")')
            lines.append('    message("--")')
            lines.append("    message(FATAL_ERROR)")
            lines.append("endif()")
            lines.append("")

    for cls in project_ir.classes:
        _emit_dep_checks(cls.name, cls.requirements)

    for iface in project_ir.interfaces:
        _emit_dep_checks(iface.name, getattr(iface, 'requirements', []))

    for impl in project_ir.implementations:
        _emit_dep_checks(impl.name, impl.requirements)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# sources.cmake
# ---------------------------------------------------------------------------

def _cmake_path(header_path: str, project_ir: IRProject) -> str:
    """Convert a repo-relative header/source path to a CMake path expression.

    E.g. ``../library/ratchet/include/virgil/crypto/ratchet/vscr_assert.h``
    → ``${CMAKE_CURRENT_LIST_DIR}/include/virgil/crypto/ratchet/vscr_assert.h``
    """
    # The paths from IROutputTarget are relative to the codegen root
    # (e.g. ../library/ratchet/...). We need them relative to library/{project}/
    project_path = project_ir.attrs.get("path", f"../library/{project_ir.name}")
    if not project_path.endswith("/"):
        project_path += "/"
    if header_path.startswith(project_path):
        rel = header_path[len(project_path):]
    elif header_path.startswith(f"../library/{project_ir.name}/"):
        rel = header_path[len(f"../library/{project_ir.name}/"):]
    else:
        rel = header_path
    return f"${{CMAKE_CURRENT_LIST_DIR}}/{rel}"


def _is_unconditional_entity(entity_kind: str, entity_name: str, attrs: dict) -> bool:
    """Determine if an entity is unconditional (no feature guard) in sources.cmake."""
    # Shared modules are unconditional
    if entity_kind == "module":
        return True
    # Enums are unconditional
    if entity_kind == "enum":
        return True
    return False


def _impl_has_private_methods(impl: IRImplementation) -> bool:
    for method in impl.methods:
        scope = method.attrs.get("scope", "")
        decl = method.attrs.get("declaration", "private")
        if scope == "private" and decl == "public":
            return True
    return False


def generate_sources_cmake(project_ir: IRProject, license_text: str = "") -> str:
    """Generate ``sources.cmake`` content for a project."""
    PREFIX = project_ir.prefix.upper()
    ns = project_ir.include_namespace  # e.g. "virgil/crypto/ratchet"
    lines: list[str] = []

    lines.append(_cmake_prologue(license_text))
    lines.append("")
    lines.append(_target_check(project_ir.name))
    lines.append("")

    # Platform checks
    lines.append("include(CheckIncludeFiles)")
    lines.append(f"check_include_files(assert.h {PREFIX}_HAVE_ASSERT_H)")
    lines.append(f"check_include_files(stdatomic.h {PREFIX}_HAVE_STDATOMIC_H)")
    lines.append("")

    # configure_file for platform.h.in
    has_platform = any(
        m.attrs.get("has_cmakedefine") == "1" or "platform" in m.name
        for m in project_ir.modules + project_ir.dependency_modules
    )
    if has_platform:
        lines.append("configure_file(")
        lines.append(f'        "${{CMAKE_CURRENT_LIST_DIR}}/include/{ns}/{project_ir.prefix}_platform.h.in"')
        lines.append(f'        "${{CMAKE_CURRENT_BINARY_DIR}}/include/{ns}/{project_ir.prefix}_platform.h"')
        lines.append("        )")
        lines.append("")

    # Collect all files grouped by: unconditional headers, featured headers, unconditional sources, featured sources
    uncond_headers: list[str] = []
    uncond_sources: list[str] = []
    featured_headers: list[tuple[str, str]] = []  # (feature_flag, path)
    featured_sources: list[tuple[str, str]] = []
    public_headers: list[str] = []  # For MACOSX_PACKAGE_LOCATION

    def _add_output(output: IROutputTarget, feature: str | None, *, has_defs: bool = False, defs_output: IROutputTarget | None = None) -> None:
        header_cmake = _cmake_path(output.header_path, project_ir)
        source_cmake = _cmake_path(output.source_path, project_ir)
        if output.header_visibility == "public":
            public_headers.append(header_cmake)

        if feature:
            featured_headers.append((feature, header_cmake))
            featured_sources.append((feature, source_cmake))
            if has_defs and defs_output:
                defs_h = _cmake_path(defs_output.header_path, project_ir)
                defs_c = _cmake_path(defs_output.source_path, project_ir)
                featured_headers.append((feature, defs_h))
                featured_sources.append((feature, defs_c))
        else:
            uncond_headers.append(header_cmake)
            uncond_sources.append(source_cmake)

    # Modules (unconditional)
    all_modules = project_ir.modules + project_ir.dependency_modules
    for mod in all_modules:
        output = cast(IROutputTarget, mod.output)
        if mod.attrs.get("has_cmakedefine") == "1":
            # Platform module: header comes from configure_file, no .c source
            # The .h.in is listed as a header, configured .h added separately below
            uncond_headers.append(f"${{CMAKE_CURRENT_LIST_DIR}}/include/{ns}/{project_ir.prefix}_{snake_name(mod.name)}.h.in")
        else:
            _add_output(output, None)

    # Platform header (configured, unconditional)
    if has_platform:
        platform_h = f"${{CMAKE_CURRENT_BINARY_DIR}}/include/{ns}/{project_ir.prefix}_platform.h"
        uncond_headers.append(platform_h)
        public_headers.append(platform_h)

    # Enums (unconditional)
    for enum in project_ir.enums:
        output = cast(IROutputTarget, enum.output)
        _add_output(output, None)

    # Classes (feature-gated)
    for cls in project_ir.classes:
        output = cast(IROutputTarget, cls.output)
        flag = feature_flag_name(project_ir.prefix, cls.name)
        # Determine if class has a separate _defs module
        is_value_type = cls.attrs.get("is_value_type") in {"1", "true"}
        context = cls.attrs.get("context", "public")
        cls_scope = cls.attrs.get("scope", "public")
        has_lifecycle = cls.attrs.get("lifecycle") != "none"
        inline_struct = is_value_type or not has_lifecycle or (cls_scope == "internal" and context == "public")
        has_defs = not inline_struct and context != "none"
        defs_out = class_defs_output(output, context=context, scope=cls_scope) if has_defs else None
        _add_output(output, flag, has_defs=has_defs, defs_output=defs_out)

    # Interfaces (feature-gated) — dispatch module + API module
    for iface in project_ir.interfaces:
        iface_output = cast(IROutputTarget, iface.output)
        flag = feature_flag_name(project_ir.prefix, iface.name)
        iface_h = _cmake_path(iface_output.header_path, project_ir)
        # Dispatch module (main) — public header for framework packaging
        featured_headers.append((flag, iface_h))
        featured_sources.append((flag, _cmake_path(iface_output.source_path, project_ir)))
        if iface_output.header_visibility == "public":
            public_headers.append(iface_h)
        # API module (private header — not in framework)
        api_out = interface_api_output(iface_output)
        featured_headers.append((flag, _cmake_path(api_out.header_path, project_ir)))
        featured_sources.append((flag, _cmake_path(api_out.source_path, project_ir)))

    # Implementations (feature-gated) — main + defs + internal [+ private]
    for impl in project_ir.implementations:
        impl_output = cast(IROutputTarget, impl.output)
        flag = feature_flag_name(project_ir.prefix, impl.name)
        impl_h = _cmake_path(impl_output.header_path, project_ir)
        # Main module — public header for framework packaging
        featured_headers.append((flag, impl_h))
        featured_sources.append((flag, _cmake_path(impl_output.source_path, project_ir)))
        if impl_output.header_visibility == "public":
            public_headers.append(impl_h)
        # Defs module
        defs_out = implementation_defs_output(impl_output)
        featured_headers.append((flag, _cmake_path(defs_out.header_path, project_ir)))
        featured_sources.append((flag, _cmake_path(defs_out.source_path, project_ir)))
        # Internal module
        internal_out = implementation_internal_output(impl_output)
        featured_headers.append((flag, _cmake_path(internal_out.header_path, project_ir)))
        featured_sources.append((flag, _cmake_path(internal_out.source_path, project_ir)))
        # Private module (when impl has scope="private" methods)
        if _impl_has_private_methods(impl):
            private_out = implementation_private_output(impl_output)
            featured_headers.append((flag, _cmake_path(private_out.header_path, project_ir)))

    # Infrastructure files (unconditional when project has interfaces)
    # These are auto-generated by the C backend for projects with interfaces/implementations.
    if project_ir.interfaces:
        prefix = project_ir.prefix
        # api module: generic API type infrastructure
        uncond_headers.append(f"${{CMAKE_CURRENT_LIST_DIR}}/include/{ns}/{prefix}_api.h")
        public_headers.append(f"${{CMAKE_CURRENT_LIST_DIR}}/include/{ns}/{prefix}_api.h")
        uncond_headers.append(f"${{CMAKE_CURRENT_LIST_DIR}}/include/{ns}/private/{prefix}_api_private.h")
        uncond_sources.append(f"${{CMAKE_CURRENT_LIST_DIR}}/src/{prefix}_api.c")
        uncond_sources.append(f"${{CMAKE_CURRENT_LIST_DIR}}/src/{prefix}_api_private.c")
        # impl private module
        uncond_headers.append(f"${{CMAKE_CURRENT_LIST_DIR}}/include/{ns}/private/{prefix}_impl_private.h")

    # Umbrella headers (unconditional, public for framework packaging)
    pub_umbrella = f"${{CMAKE_CURRENT_LIST_DIR}}/include/{ns}/{project_ir.prefix}_{project_ir.name}_public.h"
    uncond_headers.append(pub_umbrella)
    public_headers.append(pub_umbrella)
    uncond_headers.append(f"${{CMAKE_CURRENT_LIST_DIR}}/include/{ns}/private/{project_ir.prefix}_{project_ir.name}_private.h")

    # MACOSX_PACKAGE_LOCATION for public headers
    for h in public_headers:
        lines.append("set_property(")
        lines.append(f'    SOURCE "{h}"')
        lines.append('    PROPERTY MACOSX_PACKAGE_LOCATION "Headers"')
        lines.append(")")
        lines.append("")

    # target_sources()
    lines.append(f"target_sources({project_ir.name}")
    lines.append("    PRIVATE")

    # Unconditional headers
    for h in uncond_headers:
        lines.append(f'            "{h}"')

    # Featured headers
    for flag, h in featured_headers:
        lines.append(f'            "$<$<BOOL:${{{flag}}}>:{h}>"')

    # Blank line between headers and sources
    lines.append("")

    # Unconditional sources
    for s in uncond_sources:
        lines.append(f'            "{s}"')

    # Featured sources
    for flag, s in featured_sources:
        lines.append(f'            "$<$<BOOL:${{{flag}}}>:{s}>"')

    lines.append("        )")
    lines.append("")

    # target_include_directories()
    lines.append(f"target_include_directories({project_ir.name}")
    lines.append("        PUBLIC")
    lines.append(f"            $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}/include>")
    lines.append(f"            $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}/include/{ns}>")
    lines.append(f"            $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}/include/{ns}/private>")
    lines.append(f"            $<BUILD_INTERFACE:${{CMAKE_CURRENT_BINARY_DIR}}/include/{ns}>")
    lines.append(f"            $<BUILD_INTERFACE:${{CMAKE_CURRENT_BINARY_DIR}}/include/{ns}/private>")
    lines.append(f"            $<BUILD_INTERFACE:${{CMAKE_CURRENT_LIST_DIR}}/src>")
    lines.append(f"            $<INSTALL_INTERFACE:${{CMAKE_INSTALL_INCLUDEDIR}}>")
    lines.append("        )")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API — generate all three CMake files
# ---------------------------------------------------------------------------

def generate_cmake_files(project_ir: IRProject, license_text: str = "") -> list[tuple[str, str]]:
    """Generate all three CMake files for a project.

    Returns a list of (relative_path, content) tuples where the path is
    relative to the repo root (e.g. ``library/ratchet/sources.cmake``).
    """
    project_path = project_ir.attrs.get("path", f"../library/{project_ir.name}")
    # Normalize: ../library/ratchet → library/ratchet/
    if project_path.startswith("../"):
        project_path = project_path[3:]
    if not project_path.endswith("/"):
        project_path += "/"

    return [
        (f"{project_path}sources.cmake", generate_sources_cmake(project_ir, license_text)),
        (f"{project_path}features.cmake", generate_features_cmake(project_ir, license_text)),
        (f"{project_path}definitions.cmake", generate_definitions_cmake(project_ir, license_text)),
    ]


# ---------------------------------------------------------------------------
# External library cmake generation
# ---------------------------------------------------------------------------

def _render_cmake_default(value: str) -> str:
    """Convert a feature default attribute value to a CMake option default token.

    ``"on"`` → ``ON``, ``"off"`` → ``OFF``, ``${VAR}`` → ``${VAR}`` (verbatim,
    no quotes — CMake resolves variable references at configure time).
    """
    if value.lower() == "off":
        return "OFF"
    if value.startswith("${"):
        return value
    return "ON"


def _emit_require_check(lines: list[str], source_flag: str, req: IRFeatureRequire, prefix: str) -> None:
    """Append FATAL_ERROR blocks for one requirement clause."""
    dep_flags = [feature_flag_name(prefix, alt) for alt in req.alternatives]
    if not dep_flags:
        return
    if len(dep_flags) == 1:
        dep = dep_flags[0]
        lines.append(f"if({source_flag} AND NOT {dep})")
        lines.append('    message("-- error --")')
        lines.append('    message("--")')
        lines.append(f'    message("Feature {source_flag} depends on the feature:")')
        lines.append(f'    message("     {dep} - which is disabled.")')
        lines.append('    message("--")')
        lines.append("    message(FATAL_ERROR)")
        lines.append("endif()")
        lines.append("")
    else:
        or_expr = " OR ".join(dep_flags)
        lines.append(f"if({source_flag} AND NOT ({or_expr}))")
        lines.append('    message("-- error --")')
        lines.append('    message("--")')
        lines.append(f'    message("Feature {source_flag} requires at least one of:")')
        for dep in dep_flags:
            lines.append(f'    message("     {dep}")')
        lines.append('    message("--")')
        lines.append("    message(FATAL_ERROR)")
        lines.append("endif()")
        lines.append("")


def generate_external_library_features_cmake(lib_ir: IRExternalLibrary, license_text: str = "") -> str:
    """Generate ``features.cmake`` content for an external thirdparty library."""
    prefix = lib_ir.prefix
    lines: list[str] = []

    lines.append(_cmake_prologue(license_text))
    lines.append("")

    # Resolve the LIBRARY option default from an explicit <feature name="library"> if present.
    library_default = "ON"
    for feat in lib_ir.features:
        if feat.name == "library":
            library_default = _render_cmake_default(feat.attrs.get("default", "on"))
            break

    library_flag = f"{prefix.upper()}_LIBRARY"
    lines.append(f'option({library_flag} "Enable build of the \'{lib_ir.name}\' library" {library_default})')

    non_library_features = [f for f in lib_ir.features if f.name != "library"]
    for feat in non_library_features:
        flag = feature_flag_name(prefix, feat.name)
        default = _render_cmake_default(feat.attrs.get("default", "on"))
        desc = feat.description.replace("\n", " ").replace('"', '\\"').strip() or f"Enable feature '{feat.name}'."
        lines.append(f'option({flag} "{desc}" {default})')

    # mark_as_advanced block
    lines.append("mark_as_advanced(")
    lines.append(f"        {library_flag}")
    for feat in non_library_features:
        lines.append(f"        {feature_flag_name(prefix, feat.name)}")
    lines.append("        )")

    # Per-feature dependency checks
    has_checks = False
    for feat in lib_ir.features:
        flag = feature_flag_name(prefix, feat.name) if feat.name != "library" else library_flag
        for req in feat.requires:
            if not has_checks:
                lines.append("")
                has_checks = True
            _emit_require_check(lines, flag, req, prefix)

    # Library-level mutex / mandatory-one-of checks (e.g. ed25519)
    for lib_req in lib_ir.library_requires:
        if not has_checks:
            lines.append("")
            has_checks = True
        flags = [feature_flag_name(prefix, alt) for alt in lib_req.alternatives]
        # Pairwise mutex: no two may be enabled simultaneously
        for i, flag_a in enumerate(flags):
            for flag_b in flags[i + 1:]:
                lines.append(f"if({flag_a} AND {flag_b})")
                lines.append('    message("-- error --")')
                lines.append('    message("--")')
                lines.append(f'    message("Feature {flag_a} is enabled and alternative feature:")')
                lines.append(f'    message("     {flag_b} is enabled too.")')
                lines.append('    message("--")')
                lines.append("    message(FATAL_ERROR)")
                lines.append("endif()")
                lines.append("")
        # At least one must be enabled
        or_expr = " OR ".join(flags)
        flag_list = ", ".join(flags)
        lines.append(f"if(NOT ({or_expr}))")
        lines.append('    message("-- error --")')
        lines.append('    message("--")')
        lines.append('    message("One of the features must be enabled:")')
        lines.append(f'    message("     {flag_list}.")')
        lines.append('    message("--")')
        lines.append("    message(FATAL_ERROR)")
        lines.append("endif()")
        lines.append("")

    return "\n".join(lines) + "\n"


def generate_external_library_cmake_files(lib_ir: IRExternalLibrary, license_text: str = "") -> list[tuple[str, str]]:
    """Generate cmake files for an external library.

    Returns ``[(relative_path, content)]`` tuples relative to the repo root.
    Currently only ``features.cmake`` is generated.
    """
    path = lib_ir.path
    if path.startswith("../"):
        path = path[3:]
    if not path.endswith("/"):
        path += "/"
    return [(f"{path}features.cmake", generate_external_library_features_cmake(lib_ir, license_text))]
