"""Tests for project-global impl infrastructure module rendering.

Covers: api, api_private, impl, impl_private modules generated by
render_api_c_module, render_api_private_c_module, render_impl_c_module,
render_impl_private_c_module in project_c_backend.py.
"""
from __future__ import annotations

import unittest
import xml.etree.ElementTree as ET

from tools.codegen.project_ir import project_to_ir
from tools.codegen.project_source import load_named_project_source
from tools.codegen.project_c_backend import (
    render_api_c_module,
    render_api_private_c_module,
    render_impl_c_module,
    render_impl_private_c_module,
    discover_renderers,
)
from tools.codegen.common_bootstrap import direct_c_renderers_for_project


def _foundation_ir():
    return project_to_ir(load_named_project_source("foundation", "."))


def _common_ir():
    return project_to_ir(load_named_project_source("common", "."))


class TestApiModule(unittest.TestCase):
    """Tests for render_api_c_module."""

    @classmethod
    def setUpClass(cls):
        cls.pir = _foundation_ir()
        cls.root = render_api_c_module(cls.pir)

    def test_root_element(self):
        self.assertEqual(self.root.tag, "c_module")
        self.assertEqual(self.root.attrib["name"], "vscf_api")
        self.assertEqual(self.root.attrib["scope"], "public")

    def test_api_tag_enum_exists(self):
        enum = self.root.find(".//c_enum[@name='vscf_api_tag_t']")
        self.assertIsNotNone(enum, "api_tag enum must exist")

    def test_api_tag_enum_has_begin_and_end(self):
        enum = self.root.find(".//c_enum[@name='vscf_api_tag_t']")
        constants = enum.findall("c_constant")
        names = [c.attrib["name"] for c in constants]
        self.assertEqual(names[0], "vscf_api_tag_BEGIN")
        self.assertEqual(names[-1], "vscf_api_tag_END")
        # BEGIN has value 0
        self.assertEqual(constants[0].attrib["value"], "0")

    def test_api_tag_enum_has_all_interfaces(self):
        enum = self.root.find(".//c_enum[@name='vscf_api_tag_t']")
        constants = enum.findall("c_constant")
        # Exclude BEGIN and END
        iface_constants = [c.attrib["name"] for c in constants[1:-1]]
        iface_names_from_ir = sorted(i.name for i in self.pir.interfaces)
        expected = [f"vscf_api_tag_{n.replace(' ', '_').upper()}" for n in iface_names_from_ir]
        self.assertEqual(iface_constants, expected)
        # Must match the reference count (34 interfaces)
        self.assertEqual(len(iface_constants), 34)

    def test_api_tag_enum_sorted_alphabetically(self):
        enum = self.root.find(".//c_enum[@name='vscf_api_tag_t']")
        constants = enum.findall("c_constant")
        iface_names = [c.attrib["name"] for c in constants[1:-1]]
        self.assertEqual(iface_names, sorted(iface_names))

    def test_api_t_forward_declaration(self):
        struct = self.root.find(".//c_struct[@name='vscf_api_t']")
        self.assertIsNotNone(struct, "api_t struct must exist")
        self.assertEqual(struct.attrib["declaration"], "public")
        self.assertEqual(struct.attrib["definition"], "external")

    def test_includes_library(self):
        includes = [inc.attrib["file"] for inc in self.root.findall("c_include")]
        self.assertIn("vscf_library.h", includes)


class TestApiPrivateModule(unittest.TestCase):
    """Tests for render_api_private_c_module."""

    @classmethod
    def setUpClass(cls):
        cls.pir = _foundation_ir()
        cls.root = render_api_private_c_module(cls.pir)

    def test_root_element(self):
        self.assertEqual(self.root.attrib["name"], "vscf_api_private")
        self.assertEqual(self.root.attrib["scope"], "private")

    def test_api_t_struct_definition(self):
        struct = self.root.find(".//c_struct[@name='vscf_api_t']")
        self.assertIsNotNone(struct, "api_t struct definition must exist")
        self.assertEqual(struct.attrib["declaration"], "external")
        self.assertEqual(struct.attrib["definition"], "public")

    def test_api_t_has_api_tag_property(self):
        struct = self.root.find(".//c_struct[@name='vscf_api_t']")
        props = struct.findall("c_property")
        prop_names = [p.attrib["name"] for p in props]
        self.assertIn("api_tag", prop_names)

    def test_api_t_has_impl_tag_property(self):
        struct = self.root.find(".//c_struct[@name='vscf_api_t']")
        props = struct.findall("c_property")
        prop_names = [p.attrib["name"] for p in props]
        self.assertIn("impl_tag", prop_names)

    def test_includes(self):
        includes = [inc.attrib["file"] for inc in self.root.findall("c_include")]
        self.assertIn("vscf_library.h", includes)
        self.assertIn("vscf_api.h", includes)
        self.assertIn("vscf_impl.h", includes)


class TestImplModule(unittest.TestCase):
    """Tests for render_impl_c_module."""

    @classmethod
    def setUpClass(cls):
        cls.pir = _foundation_ir()
        cls.root = render_impl_c_module(cls.pir)

    def test_impl_tag_enum_exists(self):
        enum = self.root.find(".//c_enum[@name='vscf_impl_tag_t']")
        self.assertIsNotNone(enum, "impl_tag enum must exist")

    def test_impl_tag_enum_has_begin_and_end(self):
        enum = self.root.find(".//c_enum[@name='vscf_impl_tag_t']")
        constants = enum.findall("c_constant")
        names = [c.attrib["name"] for c in constants]
        self.assertEqual(names[0], "vscf_impl_tag_BEGIN")
        self.assertEqual(names[-1], "vscf_impl_tag_END")
        self.assertEqual(constants[0].attrib["value"], "0")

    def test_impl_tag_enum_has_all_implementations(self):
        enum = self.root.find(".//c_enum[@name='vscf_impl_tag_t']")
        constants = enum.findall("c_constant")
        impl_constants = [c.attrib["name"] for c in constants[1:-1]]
        impl_names_from_ir = sorted(i.name for i in self.pir.implementations)
        expected = [f"vscf_impl_tag_{n.replace(' ', '_').upper()}" for n in impl_names_from_ir]
        self.assertEqual(impl_constants, expected)
        self.assertEqual(len(impl_constants), 58)

    def test_impl_tag_enum_sorted_alphabetically(self):
        enum = self.root.find(".//c_enum[@name='vscf_impl_tag_t']")
        constants = enum.findall("c_constant")
        impl_names = [c.attrib["name"] for c in constants[1:-1]]
        # The generator orders the enum by the sorted IR implementation names
        # (space-separated, lower-case: see project_c_backend `sorted(i.name ...)`),
        # then transforms each to the vscf_impl_tag_<UPPER_UNDERSCORE> constant.
        # Re-sorting the *transformed* strings would use a different key: for
        # adjacent names like "chunk cipher"/"chunked alg info", ' ' (0x20) sorts
        # before 'e' whereas '_' (0x5F) sorts after 'E', flipping the order. So
        # compare against the IR-name sort key the generator actually uses.
        expected = [
            f"vscf_impl_tag_{n.replace(' ', '_').upper()}"
            for n in sorted(i.name for i in self.pir.implementations)
        ]
        self.assertEqual(impl_names, expected)

    def test_impl_t_forward_declaration(self):
        struct = self.root.find(".//c_struct[@name='vscf_impl_t']")
        self.assertIsNotNone(struct, "impl_t struct must exist")
        self.assertEqual(struct.attrib["declaration"], "public")
        self.assertEqual(struct.attrib["definition"], "external")

    def test_dispatch_methods_present(self):
        methods = self.root.findall(".//c_method")
        method_names = {m.attrib["name"] for m in methods}
        expected = {
            "vscf_impl_api",
            "vscf_impl_tag",
            "vscf_impl_cleanup",
            "vscf_impl_delete",
            "vscf_impl_destroy",
            "vscf_impl_shallow_copy",
            "vscf_impl_shallow_copy_const",
        }
        self.assertEqual(method_names, expected)

    def test_dispatch_method_api_has_code(self):
        method = self.root.find(".//c_method[@name='vscf_impl_api']")
        code = method.find("c_code")
        self.assertIsNotNone(code, "api method must have generated code")
        self.assertIn("find_api_cb", code.text)

    def test_dispatch_method_tag_has_code(self):
        method = self.root.find(".//c_method[@name='vscf_impl_tag']")
        code = method.find("c_code")
        self.assertIn("impl_tag", code.text)

    def test_dispatch_method_cleanup_has_code(self):
        method = self.root.find(".//c_method[@name='vscf_impl_cleanup']")
        code = method.find("c_code")
        self.assertIn("self_cleanup_cb", code.text)

    def test_dispatch_method_delete_has_code(self):
        method = self.root.find(".//c_method[@name='vscf_impl_delete']")
        code = method.find("c_code")
        self.assertIn("self_delete_cb", code.text)

    def test_dispatch_method_destroy_has_code(self):
        method = self.root.find(".//c_method[@name='vscf_impl_destroy']")
        code = method.find("c_code")
        self.assertIn("impl_delete", code.text)

    def test_dispatch_method_shallow_copy_has_code(self):
        method = self.root.find(".//c_method[@name='vscf_impl_shallow_copy']")
        code = method.find("c_code")
        self.assertIn("ATOMIC_COMPARE_EXCHANGE_WEAK", code.text)

    def test_dispatch_method_shallow_copy_const_has_code(self):
        method = self.root.find(".//c_method[@name='vscf_impl_shallow_copy_const']")
        code = method.find("c_code")
        self.assertIn("shallow_copy", code.text)

    def test_includes(self):
        includes = [inc.attrib["file"] for inc in self.root.findall("c_include")]
        self.assertIn("vscf_library.h", includes)
        self.assertIn("vscf_api.h", includes)

    def test_private_includes(self):
        private_includes = [inc.attrib["file"] for inc in self.root.findall("c_include[@scope='private']")]
        self.assertIn("vscf_impl_private.h", private_includes)
        self.assertIn("vscf_assert.h", private_includes)
        self.assertIn("vscf_atomic.h", private_includes)


class TestImplPrivateModule(unittest.TestCase):
    """Tests for render_impl_private_c_module."""

    @classmethod
    def setUpClass(cls):
        cls.pir = _foundation_ir()
        cls.root = render_impl_private_c_module(cls.pir)

    def test_root_element(self):
        self.assertEqual(self.root.attrib["name"], "vscf_impl_private")
        self.assertEqual(self.root.attrib["scope"], "private")

    def test_callback_typedefs(self):
        callbacks = self.root.findall("c_callback")
        cb_names = {c.attrib["name"] for c in callbacks}
        expected = {
            "vscf_impl_cleanup_fn",
            "vscf_impl_delete_fn",
            "vscf_impl_find_api_fn",
        }
        self.assertEqual(cb_names, expected)

    def test_impl_info_t_struct(self):
        struct = self.root.find(".//c_struct[@name='vscf_impl_info_t']")
        self.assertIsNotNone(struct, "impl_info_t struct must exist")
        self.assertEqual(struct.attrib["declaration"], "public")
        self.assertEqual(struct.attrib["definition"], "public")
        props = [p.attrib["name"] for p in struct.findall("c_property")]
        self.assertEqual(props, ["impl_tag", "find_api_cb", "self_cleanup_cb", "self_delete_cb"])

    def test_impl_t_struct_definition(self):
        struct = self.root.find(".//c_struct[@name='vscf_impl_t']")
        self.assertIsNotNone(struct, "impl_t struct definition must exist")
        self.assertEqual(struct.attrib["declaration"], "external")
        self.assertEqual(struct.attrib["definition"], "public")
        props = [p.attrib["name"] for p in struct.findall("c_property")]
        self.assertEqual(props, ["info", "refcnt"])

    def test_includes(self):
        includes = [inc.attrib["file"] for inc in self.root.findall("c_include")]
        self.assertIn("vscf_library.h", includes)
        self.assertIn("vscf_impl.h", includes)
        self.assertIn("vscf_atomic.h", includes)
        self.assertIn("vscf_api.h", includes)


class TestCommonProjectNoInfra(unittest.TestCase):
    """Common project has no interfaces/implementations; no infra modules should appear."""

    def test_no_impl_infra_in_common(self):
        renderers = direct_c_renderers_for_project("common", ".")
        for key in renderers:
            self.assertNotIn("vscf_api", key, f"common should not have impl infrastructure: {key}")
            self.assertNotIn("vscf_impl", key, f"common should not have impl infrastructure: {key}")

    def test_common_has_no_interfaces(self):
        pir = _common_ir()
        self.assertEqual(len(pir.interfaces), 0)
        self.assertEqual(len(pir.implementations), 0)


class TestDiscoveryRegistration(unittest.TestCase):
    """Verify that impl infrastructure modules are registered in discover_renderers for foundation."""

    @classmethod
    def setUpClass(cls):
        cls.renderers = direct_c_renderers_for_project("foundation", ".")

    def test_api_module_registered(self):
        self.assertIn("c_module_vscf_api.xml", self.renderers)

    def test_api_private_module_registered(self):
        self.assertIn("c_module_vscf_api_private.xml", self.renderers)

    def test_impl_module_registered(self):
        self.assertIn("c_module_vscf_impl.xml", self.renderers)

    def test_impl_private_module_registered(self):
        self.assertIn("c_module_vscf_impl_private.xml", self.renderers)


if __name__ == "__main__":
    unittest.main()
