package ratchet

const TEST_CURVE_PRIVATE_KEY = "MC4CAQAwBQYDK2VuBCIEIE4VNkJKhPPYPCYBPjwStxQOdp2HRApEpvUP7Q2EPTaS"
const TEST_CURVE_PUBLIC_KEY = "MCowBQYDK2VuAyEAqaJunUCdIr9tcRt6EB0Avs+HapzHURQkBc/4S2kJczs="
const TEST_CURVE_PUBLIC_KEY_RAW = "qaJunUCdIr9tcRt6EB0Avs+HapzHURQkBc/4S2kJczs="
const TEST_CURVE_PUBLIC_ID = "5BBfhHC7reQ="

const TEST_ED_PRIVATE_KEY = "MC4CAQAwBQYDK2VwBCIEILnATNiEWzN688ngZCTcj4RPCBCd+B/ALcF+n50NSO2E"
const TEST_ED_PUBLIC_KEY = "MCowBQYDK2VwAyEAfOKTjHjkZ8KIl54Bwn/VRpsUsdpsAThbE9QIVWztv84="

const TEST_MESSAGE_DATA = "zEhJfiHxsCoDJVY5oG3zJyPgJ/EdrckT11tpLYCzpOgsPuDorYt3nH/6dxqvm82QU935rc6J4VPKcUBtanu6UY+ZvMWFC2qSsQSmG0+KeIC1pUW84B/O2kZ4qHCBwn7lY1O5Yg8AXUoDRhfrpn5e4kyAKnUJC/GQzBJxlbfVnKk="
const TEST_MESSAGE_RAW_KEY1 = "s44+07H1ZfuAuYj/FGLNxXoM48u1vZTWszVPnZw1BI8="
const TEST_MESSAGE_RAW_KEY2 = "7xva6MvxNZqY2tYdZ4bnWy4lJlduM0qbZcwL+Qz3xFg="
const TEST_MESSAGE_RAW_KEY3 = "sAlpBAL/fAsrKn2Ia6OlhAF28mUYFiqjvwakDxmCqos="
const TEST_MESSAGE_RAW_KEY4 = "Tk7lAbgRwgjwr9d20fLZ/+9XVx0O2kDZf7b0Jv2I4Ys="
const TEST_MESSAGE_RAW_KEY5 = "jOubgqAhTneaujqJn9Ai4qedRs4JkENuTr2nMFr2ohA="
