name: build
on: [push]
jobs:
  build-macos:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.0.1
      - uses: actions/checkout@v2
      - name: Configure toolchain
        run: |
          cmake --version
          python3 --version
          pip3 install protobuf grpcio-tools
      - name: Configure project
        run: >
          cmake -S. -Bbuild
          -DVIRGIL_C_MT_TESTING=ON
          -DENABLE_BENCHMARKING=ON
          -DVIRGIL_PROGRAMS=ON
      - name: Build project
        run: cmake --build build -- -j$(sysctl -n hw.physicalcpu)
      - name: Run tests
        run: ctest --output-on-failure
        working-directory: build
  build-xcframeworks:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - uses: actions/checkout@v2
      - name: Configure toolchain
        run: |
          cmake --version
          python3 --version
          pip3 install protobuf grpcio-tools
      - name: Build Frameworks
        run: ./scripts/build_apple_frameworks.sh
      - name: Check that SPM has correspond xcframeworks hash
        run: |
          ./scripts/update_binaries.sh
          if ! git diff-index --quiet HEAD --; then
            echo "SPM config Package.swift handles outdates xcframework hash"
            exit 1
          fi
