name: build-macos-php
on:
  push:
    branches:
      - "main"
      - "develop"
      - "release/**"
      - "hotfix/**"
    tags:
      - "*"
jobs:
  build-macos-php:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
        php-version: ["8.2", "8.3"]
        arch: [x86_64, arm64]
        include:
          - arch: x86_64
            optimizations: -DED25519_REF10=OFF -DED25519_AMD64_RADIX_64_24K=ON
            should_test: true
          - arch: arm64
            optimizations: -DED25519_REF10=ON
            should_test: false
    name: PHP ${{ matrix.php-version }} build on ${{ matrix.os }} for arch ${{ matrix.arch }}
    steps:
      - name: Install PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Check PHP Version
        run: php -v
      - uses: actions/checkout@v4
      - name: Configure toolchain
        run: |
          cmake --version
          python3 --version
          pip3 install protobuf grpcio-tools
      - name: Configure project
        run: >
          cmake -Cconfigs/php-config.cmake \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
              -DVIRGIL_PACKAGE_PLATFORM_ARCH=${{ matrix.arch }} \
              -DVIRGIL_PACKAGE_LANGUAGE_VERSION=${{ matrix.php-version }} \
              -DCPACK_OUTPUT_FILE_PREFIX=php \
              -DENABLE_CLANGFORMAT=OFF \
              ${{ matrix.optimizations }} \
              -Bbuild -S.
      - name: Build project
        run: cmake --build build -- -j$(sysctl -n hw.physicalcpu)
      - name: Test project
        if: ${{ matrix.should_test }}
        working-directory: build
        run: ctest --verbose
      - name: Package project
        working-directory: build
        run: cpack
      - name: Attach artifacts to the release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/php/*.tar.gz
