name: build-php
on:
  push:
    branches:
      - "**"
jobs:
  build-linux:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ["8.2", "8.3", "8.4"]
    name: PHP ${{ matrix.php-version }} build on ${{ matrix.operating-system }}
    steps:
      - name: Install PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Check PHP Version
        run: php -v
      - uses: actions/checkout@v3
      - name: Configure toolchain
        run: |
          sudo apt update
          cmake --version
          python3 --version
          pip3 list --outdated
          pip3 install -U protobuf grpcio-tools
          php --version
      - name: Configure project
        run: >
          cmake -Cconfigs/php-config.cmake \
              -DCMAKE_BUILD_TYPE=Release \
              -DVIRGIL_PACKAGE_PLATFORM_ARCH=$(uname -m) \
              -DVIRGIL_PACKAGE_LANGUAGE_VERSION=${{ matrix.php-version }} \
              -DCPACK_OUTPUT_FILE_PREFIX=php \
              -DENABLE_CLANGFORMAT=OFF \
              -DED25519_AMD64_RADIX_64_24K=ON -DED25519_REF10=OFF \
              -Bbuild -S.
      - name: Build project
        run: cmake --build build -- -j$(nproc)
      - name: Test project
        working-directory: build
        run: ctest --verbose
      - name: Package project
        working-directory: build
        run: cpack
      - name: Attach artifacts to the release
        working-directory: build
        run: ls -l php
