name: build
on:
  push:
    branches:
      - main
      - develop
jobs:
  build-macos:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.0.1
      - uses: actions/checkout@v3
      - name: Configure toolchain
        run: |
          cmake --version
          python3 --version
          pip3 install protobuf grpcio-tools
      - name: Configure project
        run: >
          cmake -S. -Bbuild
          -DVIRGIL_C_MT_TESTING=ON
          -DENABLE_BENCHMARKING=ON
          -DVIRGIL_PROGRAMS=ON
      - name: Build project
        run: cmake --build build -- -j$(sysctl -n hw.physicalcpu)
      - name: Run tests
        run: ctest --output-on-failure
        working-directory: build

  check-xcframeworks:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.0.1
      - uses: actions/checkout@v3
      - name: Check that SPM has correspond xcframeworks hash
        run: ./scripts/check_spm_xcframeworks.sh

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Configure toolchain
        run: |
          cmake --version
          python3 --version
          pip3 install protobuf grpcio-tools
          sudo apt update
          sudo apt install valgrind
          sudo apt install cloc
      - name: Configure project
        run: >
          cmake -S. -Bbuild
            -DENABLE_HEAVY_TESTS=OFF
            -DVIRGIL_C_MT_TESTING=OFF
            -DENABLE_BENCHMARKING=ON
            -DVIRGIL_POST_QUANTUM=ON
            -DVIRGIL_PROGRAMS=ON
      - name: Build for memcheck
        run: cmake --build build -- -j$(nproc)
      - name: Run memcheck
        working-directory: build
        run: |
          ctest -T memcheck --output-on-failure
          cat Testing/Temporary/MemoryChecker.*.log
      - name: Build multi-threading tests
        run:
          cmake -S. -Bbuild -DVIRGIL_C_MT_TESTING=ON
          cmake --build build -- -j$(nproc)
      - name: Run multi-threading tests
        working-directory: build
        run: ctest -L multi-threading --output-on-failure
      - name: Run benchmarks
        run: ./build/benchmarks/foundation/bench
      - name: Calulate line of codes
        run: cmake --build build --target cloc
