name: build-macos
on:
  push:
    branches:
      - main
      - develop
jobs:
  build-macos:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.0.1
      - uses: actions/checkout@v3
      - name: Configure toolchain
        run: |
          cmake --version
          python3 --version
          pip3 install protobuf grpcio-tools
      - name: Configure project
        run: >
          cmake -S. -Bbuild
          -DVIRGIL_C_MT_TESTING=ON
          -DENABLE_BENCHMARKING=ON
          -DVIRGIL_PROGRAMS=ON
      - name: Build project
        run: cmake --build build -- -j$(sysctl -n hw.physicalcpu)
      - name: Run tests
        run: ctest --output-on-failure
        working-directory: build

  check-xcframeworks:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.0.1
      - uses: actions/checkout@v3
      - name: Check that SPM has correspond xcframeworks hash
        run: ./scripts/check_spm_xcframeworks.sh
