name: Release Swift
on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'
jobs:
  release-apple-xcframeworks:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Check Xcode
        run: |
          xcode-select -p
          xcodebuild -version
      - name: Check that SPM has correspond xcframeworks hash
        run: ./scripts/check_spm_xcframeworks.sh
      - name: Test SPM with local binaries
        run: ./scripts/run_spm_tests_with_local_binaries.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: true
          files: ./binaries/*.xcframework.zip
      - name: Check SPM with released binaries
        run: swift test
