name: Release
on:
  push:
    tags: "*"
jobs:
  release-apple-xcframeworks:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - name: Check that SPM has correspond xcframeworks hash
        run: ./scripts/check_spm_xcframeworks.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: true
          files: ./binaries/*.xcframework.zip
      - name: Check SPM
        run: swift test
      - name: Deploy Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push VSCCrypto.podspec
          pod trunk push --synchronous VirgilCryptoFoundation.podspec
          pod trunk push --synchronous VirgilCryptoPythia.podspec
          pod trunk push --synchronous VirgilCryptoRatchet.podspec
