name: Release
on:
  push:
    tags: "*"

jobs:
  release-apple-xcframeworks:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - uses: actions/checkout@v2
      - name: Configure toolchain
        run: |
          cmake --version
          python3 --version
          pip3 install protobuf grpcio-tools
      - name: Build Frameworks
        run: ./scripts/build_apple_frameworks.sh
      - name: Check that SPM has correspond xcframeworks hash
        run: |
          ./scripts/update_binaries.sh
          if ! git diff-index --quiet HEAD --; then
            echo "SPM config Package.swift handles outdates xcframework hash"
            exit 1
          fi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: ./build_apple/VSCFrameworks/*.xcframework.zip
      - name: SPM
        run: swift test
      - name: Check Cocoapods
        run: pod spec lint
      - name: Deploy Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push VSCCrypto.podspec
          pod trunk push VirgilCryptoFoundation.podspec
          pod trunk push VirgilCryptoPythia.podspec
          pod trunk push VirgilCryptoRatchet.podspec
